name: Run blktests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests-on-kernel:
    runs-on: arc-vm-dennis-block-ci
    steps:
      - name: Checkout blktests-ci
        uses: actions/checkout@v7
        with:
          repository: MaisenbacherD/blktests-ci
          ref: "fix-image-pull"

      - name: Run in VM
        uses: ./.github/actions/kubevirt-action
        with:
          container_disk_image: "ghcr.io/maisenbacherd/blktests-fedora-containerdisk:test"
          host_devices: "nvme-wdc-zn540,nvme-wdc-sn640"
          vm_artifact_upload_dir: blktests/results
          run_cmds: |
            uname -a
            cat /etc/os-release
            lsblk

            git clone https://github.com/linux-blktests/blktests.git

            cd blktests
            git checkout ci
            make

            #ATTENTION! This section formats all available NVMe devices. Be careful when changing the `runs-on` tag!
            #This step runs in a VM with the previously compiled kernel in the k8s cluster

            ./contrib/run_ci https://github.com/linux-blktests/blktests-ci-conditions/raw/main

            # Mark blktests completion for KPD report
            echo "KPD: blktests completed"

            # Output failures for KPD report
            test -f all_failures && echo "KPD: Failures:" && cat all_failures

            test -f all_failures && exit 1
            exit 0
